### ISSUE TITLE
Sqlite support for Zabbix Proxy?

### ISSUE THREAD

**Issue by execthis** [dj-wasabi/ansible-zabbix-proxy#11]
Hi dj-wasabi

First of all, thanks for your great work!
Is it planned to support zabbix proxy with sqlite3 backend? We are only using sqlite backend on our proxies because of less dependencies.

Thanks in advance & best regards
Remo

**Comment by dj-wasabi** [comment]
I don't have anything planned yet, but when someone wants it I can/will arrange something. :-)

**Comment by mgornikov** [comment]
See #16

**Comment by dj-wasabi** [comment]
I close this issue as it is already implemented.

**Comment by lauer** [comment]
Hmm, was trying to install with zabbix-proxy-sqlite3, but can't see the #16 actually completely add this feature. 
Some documentation are missing, and what I can read in the tasks, some check are missing, to really support sqlite3.

I have tried to set the `zabbix_proxy_database: sqlite3` variable, and it tries to install the right package, but I guess the PR never has been testet?

(Runningen on ubuntu 18.04)
