### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by emmetog** [dj-wasabi/ansible-zabbix-proxy#12]
Currently the latest version available in galaxy is version 0.4, but quite a lot of commits have been made since that version.

Can we get a newer release in galaxy?

**Comment by emmetog** [comment]
It's also not possible to use a commit hash as a version, are the galaxy github hooks set up correctly on this repo?

**Comment by dj-wasabi** [comment]
Hi @emmetog 

Yes, you are right. It is time to make a new release. Will try to create one tonight.

**Comment by dj-wasabi** [comment]
What do you mean with "are the galaxy github hooks set up correctly on this repo?" ?

**Comment by emmetog** [comment]
On other repositories I've found that it's possible to specify the commit hash as the version string and it works but for some reason it doesn't work for this role. I thought it was because maybe ansible galaxy hasn't been able to get the new commit hashes from github but now I'm not sure, I tried linking my fork to Galaxy but specifying the commit hash as the version string still didn't work :( I don't know why.

Forget I said anything though, a new "official" release version will do the trick.

**Comment by dj-wasabi** [comment]
I just pushed 0.5.0 to the Galaxy.

**Comment by emmetog** [comment]
Thanks @dj-wasabi !

**Comment by dj-wasabi** [comment]
Have fun!
