### ISSUE TITLE
Create database error

### ISSUE THREAD

**Issue by siye1103** [dj-wasabi/ansible-zabbix-proxy#25]
TASK [dj-wasabi.zabbix-proxy : MySQL | Create database] ************************
11:03:18
task path: /var/lib/awx/projects/zabbixproxy/roles/dj-wasabi.zabbix-proxy/tasks/mysql.yml:7
11:03:18
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "module_stderr": "sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

**Comment by dj-wasabi** [comment]
Hi @siye1103 

This is a infrastructure thing on your host. It seems you use a nfs mount to store data? I don't see what I can do to fix that. I therefor close this issue.

Kind regards,
Werner
