### ISSUE TITLE
HistoryTextCacheSize is deprecated in Zabbix 3

### ISSUE THREAD

**Issue by mamchenkov** [dj-wasabi/ansible-zabbix-proxy#3]
Hi,

first of all - thanks for all the great work on these roles! :smile: 

Trying to install Zabbix proxy 3 using version 0.3.0 of your role, and I get this, when the service is trying to restart:

```
unknown parameter "HistoryTextCacheSize" in config file "/etc/zabbix/zabbix_proxy.conf", line 236
```

According to [this spec](https://www.zabbix.org/wiki/Docs/specs/ZBXNEXT-3071#Details):

> `HistoryTextCacheSize` configuration parameter must be removed.

**Comment by dj-wasabi** [comment]
Hi,

Sorry for late reply, but this is fixed as of now (github) and will be available in the next few days on the Galaxy (0.4.0)

**Comment by dj-wasabi** [comment]
Just pushed 0.4.0 to the galaxy.

**Comment by mamchenkov** [comment]
Thanks! :+1:
