### ISSUE TITLE
agent and proxy on same host

### ISSUE THREAD

**Issue by jiri-bati-novak** [dj-wasabi/ansible-zabbix-proxy#4]
Hello,
I do use both your proxy and agent roles on same host (centos 6, if that matters), and I get "changed" status of that host on the every ansible-playbook run due to yum repo file being changed  by proxy and also proxy roles. could this be remedied? I think that root cause is difference between .repo templates...
Thank you...
JN

**Comment by dj-wasabi** [comment]
Yes, you are right. Will fix it.

**Comment by jiri-bati-novak** [comment]
Thank you :)
JN

**Comment by dj-wasabi** [comment]
Agent and proxy uses the same 'template', so they won't bother you anymore ;-)

**Comment by dj-wasabi** [comment]
Just pushed 0.4.0 to the galaxy.
