### ISSUE TITLE
Misspelling in conf template "ListenIp"

### ISSUE THREAD

**Issue by lebe-dev** [dj-wasabi/ansible-zabbix-proxy#8]
Hello

Configuration template https://github.com/dj-wasabi/ansible-zabbix-proxy/blob/master/templates/zabbix_proxy.conf.j2#L246 has misspelling

Current: ListenIp
Correct: ListenIP

**Example of error:**
> fatal: [somehost]: FAILED! => {"changed": false, "failed": true, "msg": "zabbix_proxy [27861]: unknown parameter \"ListenIp\" in config file \"/etc/zabbix/zabbix_proxy.conf\", line 208\n"}

**Comment by emmetog** [comment]
It looks correct now, this can probably be closed
